services:
  mysql:
    image: mysql:8.0
    container_name: localmysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: defaultdb
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    container_name: localredis
    ports:
      - "7379:6379"

  mongo:
    image: mongo:7
    container_name: localmongo
    ports:
      - "37017:27017"